export const MODULE_DEFINITIONS = {
  overview: {
    name: 'Overview',
    icon: 'home',
    description: 'Summarize business health and highlight operational risks across modules.',
    agents: [
      {
        id: 'overview-summary',
        title: 'Business summary agent',
        description: 'Creates a daily rollup of reviews, inbox, social, and campaign performance.',
        steps: ['Daily schedule', 'Collect module signals', 'Summarize changes', 'Share digest'],
      },
      {
        id: 'overview-risk',
        title: 'Risk detection agent',
        description: 'Flags sudden changes in sentiment, SLA misses, or performance drops.',
        steps: ['Hourly scan', 'Detect anomalies', 'Rank impact', 'Notify owner'],
      },
    ],
  },
  reviews: {
    name: 'Reviews',
    icon: 'grade',
    description: 'Automate review response, escalation, tagging, and quality monitoring workflows.',
    agents: [
      {
        id: 'reviews-response-templates',
        sectionContext: 'review-response-agents',
        title: 'Review response agent replying using templates',
        description: 'Uses pre-defined templates and responds to reviews automatically.',
        steps: ['New review trigger', 'Sentiment check', 'LLM reply draft', 'Approval or publish'],
      },
      {
        id: 'reviews-response-autonomous',
        sectionContext: 'review-response-agents',
        title: 'Review response agent replying autonomously',
        description: 'Uses AI to analyze review sentiment, generates and posts unique, context aware replies automatically.',
        steps: ['New review trigger', 'Sentiment check', 'LLM reply draft', 'Publish reply'],
      },
      {
        id: 'reviews-response-human-approval',
        sectionContext: 'review-response-agents',
        title: 'Review response agent replying after human approval',
        description: 'Uses AI to analyze review sentiment, generates and sends unique, context-aware replies for a human approval before posting.',
        steps: ['New review trigger', 'Sentiment check', 'LLM reply draft', 'Approval or publish'],
      },
      {
        id: 'reviews-response-dashboard-suggestions',
        sectionContext: 'review-response-agents',
        title: 'Review response agent suggesting replies in dashboard',
        description: 'Uses AI to analyze review sentiment, generates and shows unique, context-aware replies in the dashboard for one-click manual posting.',
        steps: ['Low rating trigger', 'Branch by urgency', 'Create ticket', 'Notify owner'],
      },
    ],
  },
  referrals: {
    name: 'Referrals',
    icon: 'featured_seasonal_and_gifts',
    description: 'Create referral requests, reminders, and conversion follow-up workflows.',
    agents: [
      {
        id: 'referrals-request',
        title: 'Referral request agent',
        description: 'Finds happy customers and sends referral requests at the right moment.',
        steps: ['Positive signal trigger', 'Check eligibility', 'Send request', 'Track response'],
      },
      {
        id: 'referrals-follow-up',
        title: 'Referral follow-up agent',
        description: 'Follows up with customers and referred leads when referral activity stalls.',
        steps: ['Referral created', 'Wait period', 'Branch by status', 'Send follow-up'],
      },
    ],
  },
  payments: {
    name: 'Payments',
    icon: 'monetization_on',
    description: 'Automate payment reminders, failed-payment recovery, and status updates.',
    agents: [
      {
        id: 'payments-reminder',
        title: 'Payment reminder agent',
        description: 'Sends friendly reminders before invoices become overdue.',
        steps: ['Due date schedule', 'Check payment status', 'Send reminder', 'Log outcome'],
      },
      {
        id: 'payments-recovery',
        title: 'Failed payment recovery agent',
        description: 'Routes failed payments through retries, customer messages, and owner alerts.',
        steps: ['Payment failed', 'Retry branch', 'Notify customer', 'Escalate unresolved'],
      },
    ],
  },
  appointments: {
    name: 'Appointments',
    icon: 'calendar_month',
    description: 'Reduce no-shows and keep appointment communications on schedule.',
    agents: [
      {
        id: 'appointments-reminder',
        title: 'Appointment reminder agent',
        description: 'Sends appointment reminders with location, service, and rescheduling context.',
        steps: ['Upcoming appointment', 'Check preferences', 'Send reminder', 'Confirm status'],
      },
      {
        id: 'appointments-no-show',
        title: 'No-show recovery agent',
        description: 'Follows up on missed appointments and helps customers rebook.',
        steps: ['No-show trigger', 'Generate message', 'Offer slots', 'Notify staff'],
      },
    ],
  },
  inbox: {
    name: 'Inbox',
    icon: 'sms',
    description: 'Triage customer conversations, suggest replies, and move high-intent leads forward.',
    agents: [
      {
        id: 'inbox-intent',
        title: 'Conversation intent routing agent',
        description: 'Classifies new messages and routes sales, support, billing, or urgent conversations.',
        steps: ['New message trigger', 'Intent classifier', 'Branch by intent', 'Assign owner'],
      },
      {
        id: 'inbox-reply',
        title: 'Inbox reply assistant',
        description: 'Creates brand-safe suggested replies for teams to review and send quickly.',
        steps: ['Message received', 'Fetch context', 'Generate reply', 'Wait for approval'],
      },
    ],
  },
  listings: {
    name: 'Listings',
    icon: 'location_on',
    description: 'Keep profile data accurate across location networks and flag sync issues.',
    agents: [
      {
        id: 'listings-scan',
        title: 'Listings scan agent',
        description: 'Checks location fields for missing or mismatched data before publishing updates.',
        steps: ['Scheduled scan', 'Validate fields', 'Create mismatch report', 'Notify POD'],
      },
      {
        id: 'listings-hours',
        title: 'Holiday hours agent',
        description: 'Detects upcoming holidays and prepares hours updates for affected locations.',
        steps: ['Weekly schedule', 'Find holidays', 'Generate updates', 'Request approval'],
      },
    ],
  },
  social: {
    name: 'Social',
    icon: 'workspaces',
    description: 'Plan, publish, monitor, and respond to social content across networks.',
    agents: [
      {
        id: 'social-publishing',
        title: 'Social publishing agent',
        description: 'Turns campaign briefs into platform-ready posts with schedule and approval steps.',
        steps: ['Campaign brief', 'Generate copy', 'Branch by channel', 'Schedule post'],
      },
      {
        id: 'social-engagement',
        title: 'Social engagement agent',
        description: 'Monitors comments and mentions, then routes engagement opportunities or risks.',
        steps: ['Mention trigger', 'Classify sentiment', 'Generate response', 'Escalate risky comments'],
      },
    ],
  },
  surveys: {
    name: 'Surveys',
    icon: 'assignment_turned_in',
    description: 'Create feedback loops that analyze survey responses and trigger follow-up.',
    agents: [
      {
        id: 'surveys-follow-up',
        sectionContext: 'survey-follow-up-agents',
        title: 'Survey follow-up agent',
        description: 'Responds to detractors, promoters, and missing fields with targeted actions.',
        steps: ['Survey submitted', 'Score branch', 'Draft follow-up', 'Create task'],
      },
      {
        id: 'surveys-response-agent',
        sectionContext: 'survey-response-agents',
        title: 'Survey response agent',
        description: 'Extracts survey details — sentiment, trends, severity, staff, competitors — then generates a personalized, on-brand response tailored to the respondent\'s history and contact properties.',
        steps: ['Survey response received', 'Survey Details Extraction', 'Response Generation'],
        nodes: [
          {
            id: 'sra-trigger-1',
            flowType: 'trigger',
            data: {
              title: 'Survey response received',
              subtype: 'When a survey response is received',
              description: 'Fires when a new survey response is submitted',
              hasAiIcon: false,
              hasToggle: true,
              toggleEnabled: true,
              stepNumber: 1,
              titlePlaceholder: 'Enter trigger name',
              descriptionPlaceholder: 'Enter description',
            },
          },
          {
            id: 'sra-task-extraction',
            flowType: 'task',
            data: {
              title: 'Survey Details Extraction',
              subtype: 'Custom',
              description: 'Extracts sentiment, topics, staff mentions, competitors, and severity',
              hasAiIcon: true,
              hasToggle: true,
              toggleEnabled: true,
              stepNumber: 2,
              titlePlaceholder: 'Enter task name',
              descriptionPlaceholder: 'Enter description',
            },
          },
          {
            id: 'sra-task-response',
            flowType: 'task',
            data: {
              title: 'Response Generation',
              subtype: 'Custom',
              description: 'Assembles a personalized survey response using extracted details',
              hasAiIcon: true,
              hasToggle: true,
              toggleEnabled: true,
              stepNumber: 3,
              titlePlaceholder: 'Enter task name',
              descriptionPlaceholder: 'Enter description',
            },
          },
        ],
        nodeDetails: {
          '__start__': {
            agentName: 'Survey response agent',
            goals: 'Analyze every survey response to extract sentiment, topics, trends, and severity, then generate a personalized response that acknowledges feedback, reinforces loyalty, and mitigates churn risk.',
            outcomes: 'Every respondent receives a timely, personalized, and on-brand reply that addresses their specific feedback, reducing churn and improving NPS.',
            locations: [],
          },
          'sra-trigger-1': {
            triggerName: 'Survey response received',
            description: 'Fires when a new survey response is submitted via email, SMS, or in-app channel',
            conditions: [
              { id: 1, fieldValue: 'survey_type', operatorValue: 'is', valueValue: 'nps' },
              { id: 2, fieldValue: 'completion_status', operatorValue: 'is', valueValue: 'completed' },
            ],
            logic: 'AND',
            conditionOptions: {
              field: [
                { value: 'survey_type', label: 'Survey type' },
                { value: 'overall_score', label: 'Overall score' },
                { value: 'completion_status', label: 'Completion status' },
                { value: 'source', label: 'Source' },
                { value: 'respondent_type', label: 'Respondent type' },
                { value: 'location', label: 'Location' },
              ],
              operator: [
                { value: 'is', label: 'is' },
                { value: 'is_not', label: 'is not' },
                { value: 'greater_than', label: 'is greater than' },
                { value: 'less_than', label: 'is less than' },
                { value: 'contains', label: 'contains' },
              ],
              value: [
                { value: 'nps', label: 'NPS' },
                { value: 'csat', label: 'CSAT' },
                { value: 'ces', label: 'CES' },
                { value: 'custom', label: 'Custom' },
                { value: 'pulse', label: 'Pulse' },
                { value: 'email', label: 'Email' },
                { value: 'sms', label: 'SMS' },
                { value: 'completed', label: 'Completed' },
                { value: 'partial', label: 'Partial' },
              ],
            },
          },
          'sra-task-extraction': {
            taskName: 'Survey Details Extraction',
            description: 'Detects what the respondent is talking about across all survey questions, maps it to the business\'s vocabulary, scores severity, identifies staff and competitors, detects score-comment mismatches and trend shifts against past responses, leverages contact custom properties for personalization context, and flags relevant business context details.',
            llmModel: 'Thinking',
            contextFields: [
              { value: 'Location.name', type: 'variable' },
              { value: 'Location.brand', type: 'variable' },
              { value: 'Location.workinghours', type: 'variable' },
              { value: 'Location.products', type: 'variable' },
              { value: 'Location.services', type: 'variable' },
              { value: 'Location.industry', type: 'variable' },
              { value: 'Survey.type', type: 'variable' },
              { value: 'Survey.questions', type: 'variable' },
              { value: 'Contact.customProperties', type: 'variable' },
              { value: 'Contact.surveyHistory', type: 'variable' },
              { value: 'Contact.lifetimeValue', type: 'variable' },
              { value: 'Contact.tenure', type: 'variable' },
              { value: 'Location.website', type: 'variable' },
            ],
            inputFields: [
              { value: 'Survey.responses', type: 'variable' },
              { value: 'Survey.overallScore', type: 'variable' },
              { value: 'Survey.openTextAnswers', type: 'variable' },
              { value: 'Survey.source', type: 'variable' },
              { value: 'Survey.completionStatus', type: 'variable' },
              { value: 'Contact.assistedBy', type: 'variable' },
              { value: 'Contact.previousScore', type: 'variable' },
              { value: 'Contact.previousRespondentType', type: 'variable' },
            ],
            systemPrompt: 'You are a Survey Intelligence Extractor. Your job is to analyze a customer\'s survey response and extract details. Be precise. Do not hallucinate. If something is not mentioned or cannot be confidently inferred, set the field to blank. Every extraction must be grounded in the actual survey responses, contact history, or contact custom properties — never invent context.\n\nUse contact custom properties to personalize severity assessment and recommendations (e.g., a high-tier customer\'s complaint carries higher business risk). Use past survey history to detect trends — improvement, deterioration, or sentiment reversals — which are stronger signals than a single response in isolation.',
            userPrompt: 'Analyze the following survey response:\nSurvey Type: {Survey.type}\nOverall Score: {Survey.overallScore}\nQuestion-Answer Pairs: {Survey.responses}\nOpen Text Answers: {Survey.openTextAnswers}\nContact Custom Properties: {Contact.customProperties}\nPrevious Survey Score: {Contact.previousScore}\nPrevious Respondent Type: {Contact.previousRespondentType}\nSurvey History: {Contact.surveyHistory}\n\nPerform all of the following:\n\n1. Language Detection — Identify the response language from open-text answers.\n\n2. Respondent Classification — Based on {Survey.type} and {Survey.overallScore}, classify the respondent (NPS: Promoter 9-10, Passive 7-8, Detractor 0-6; CSAT: Satisfied 4-5, Neutral 3, Dissatisfied 1-2; CES: Low Effort, Neutral, High Effort).\n\n3. Trend Shift Detection — Compare current classification against {Contact.previousRespondentType} and {Contact.surveyHistory}. Classify as: PROMOTER_TURNED_DETRACTOR, DETRACTOR_TURNED_PROMOTER, CONSISTENT_DETRACTOR, CONSISTENT_PROMOTER, IMPROVING, DECLINING, STABLE, or FIRST_RESPONSE.\n\n4. Topic Extraction & Offering Mapping — Identify every distinct topic mentioned. For each: extract exact phrase, map to {Location.services} or {Location.products}, determine topic-level sentiment, provide quoted snippet, tag survey question origin. Flag RECURRING_ISSUE if same complaint appeared before.\n\n5. Staff / Employee Detection — Identify any staff mentioned. For each: extract reference, match to {Contact.assistedBy}, classify sentiment, flag recurring patterns.\n\n6. Competitor Detection — Identify explicit or implied competitor mentions. For each: extract name or "unnamed competitor", identify comparison aspect, determine if comparison favors competitor, business, or is neutral.\n\n7. Score-Comment Mismatch Detection — Compare quantitative score against open-text sentiment. Flag as: HIGH_SCORE_NEGATIVE_COMMENT, LOW_SCORE_POSITIVE_COMMENT, or ALIGNED.\n\n8. Severity Assessment (Customer-Weighted) — Assess impact considering: score, emotional intensity, specificity, legal/safety mentions, churn-signal language, number of negative topics, competitor comparisons, score-comment mismatch, trend shift, recurring issues. Adjust upward for high-value contacts (enterprise tier, long tenure, high LTV, VIP). Output: severity (LOW | MEDIUM | HIGH | CRITICAL), one-sentence explanation, and escalate=true if CRITICAL or PROMOTER_TURNED_DETRACTOR for a high-value contact.\n\n9. Churn Risk Signal — Determine churn risk: NONE | LOW | MEDIUM | HIGH | IMMINENT.\n\n10. Contact Channel Recommendation — NEGATIVE + MEDIUM or higher: phone + email. NEGATIVE + LOW: email only. POSITIVE or NEUTRAL: no contact. High-value contacts: escalate one level.\n\n11. Personalization Hooks — Extract: customer tenure, last interaction date, segment/tier, prior promoter status, recurring issue context, prior recovery attempts.\n\n12. Advocacy Opportunity — If Promoter/Satisfied AND no score-comment mismatch AND CONSISTENT_PROMOTER or DETRACTOR_TURNED_PROMOTER: flag as eligible for review request or referral. Follow industry-appropriate guidelines for Healthcare or Dental.',
            outputFields: [
              { value: 'Survey.language', type: 'variable' },
              { value: 'Survey.respondentType', type: 'variable' },
              { value: 'Survey.trendShift', type: 'variable' },
              { value: 'Survey.scoreChangeMagnitude', type: 'variable' },
              { value: 'Survey.severity', type: 'variable' },
              { value: 'Survey.severityReason', type: 'variable' },
              { value: 'Survey.sentiment', type: 'variable' },
              { value: 'Survey.escalate', type: 'variable' },
              { value: 'Survey.scoreCommentMismatch', type: 'variable' },
              { value: 'Survey.churnRisk', type: 'variable' },
              { value: 'Survey.recurringIssue', type: 'variable' },
              { value: 'Topics', type: 'variable' },
              { value: 'Staff_mentions', type: 'variable' },
              { value: 'Competitor_mentions', type: 'variable' },
              { value: 'Contact_Recommendation', type: 'variable' },
              { value: 'Personalization_Hooks', type: 'variable' },
              { value: 'Advocacy_Eligible', type: 'variable' },
            ],
          },
          'sra-task-response': {
            taskName: 'Response Generation',
            description: 'Assembles the final survey response message using the drafted strategy, the extracted details, the contact\'s history, and the brand voice.',
            llmModel: 'Balanced',
            contextFields: [
              { value: 'Location.brand', type: 'variable' },
              { value: 'Location.name', type: 'variable' },
              { value: 'Location.alias', type: 'variable' },
              { value: 'Location.address', type: 'variable' },
              { value: 'Location.phone', type: 'variable' },
              { value: 'Location.email', type: 'variable' },
              { value: 'Location.workinghours', type: 'variable' },
              { value: 'Location.industry', type: 'variable' },
              { value: 'Contact.firstname', type: 'variable' },
              { value: 'Contact.lastname', type: 'variable' },
              { value: 'Contact.tenure', type: 'variable' },
              { value: 'Contact.lifecyclestage', type: 'variable' },
              { value: 'Contact.tier', type: 'variable' },
              { value: 'Contact.surveycount', type: 'variable' },
              { value: 'Contact.previousScore', type: 'variable' },
              { value: 'Contact.previousRespondentType', type: 'variable' },
              { value: 'Contact.assistedby', type: 'variable' },
              { value: 'Contact.customProperties', type: 'variable' },
              { value: 'External.season', type: 'variable' },
              { value: 'External.holiday', type: 'variable' },
              { value: 'Survey.type', type: 'variable' },
              { value: 'Survey.name', type: 'variable' },
            ],
            inputFields: [
              { value: 'survey.sentiment', type: 'variable' },
              { value: 'survey.language', type: 'variable' },
              { value: 'survey.severity', type: 'variable' },
              { value: 'survey.severityReason', type: 'variable' },
              { value: 'survey.escalate', type: 'variable' },
              { value: 'survey.respondentType', type: 'variable' },
              { value: 'survey.trendShift', type: 'variable' },
              { value: 'survey.scoreCommentMismatch', type: 'variable' },
              { value: 'survey.churnRisk', type: 'variable' },
              { value: 'survey.recurringIssue', type: 'variable' },
              { value: 'topics', type: 'variable' },
              { value: 'Staff_mentions', type: 'variable' },
              { value: 'competitor_mentions', type: 'variable' },
              { value: 'contact_recommendation.recommend_contact', type: 'variable' },
              { value: 'advocacy_eligible', type: 'variable' },
              { value: 'personalization_hooks', type: 'variable' },
              { value: 'Survey.timestamp', type: 'variable' },
              { value: 'Survey.hasOpenText', type: 'variable' },
              { value: 'Survey.completionStatus', type: 'variable' },
            ],
            systemPrompt: 'You are a Customer Experience Manager specialized in writing personalized responses to survey feedback. Your tone reflects genuine listening — surveys are solicited feedback, so the customer expects acknowledgment of what they specifically said, not generic gratitude.',
            userPrompt: 'Write a response to `{Survey.openTextAnswers}` with overall score: `{Survey.overallScore}` (Survey type: `{Survey.type}`).\n\nApply all relevant rules below:\n\nRule 0 — LANGUAGE: Reply in `{survey.language}`. If unavailable, use English.\n\nRule 1 — OPENING: If `{Contact.firstname}` exists, address by first name. If response is older than 7 days, acknowledge delay in the first line. Apply trend-shift-specific openings: PROMOTER_TURNED_DETRACTOR → acknowledge experience fell short of past visits; DETRACTOR_TURNED_PROMOTER → warmly acknowledge the improvement journey; CONSISTENT_PROMOTER → appreciate ongoing loyalty. If `{Survey.hasOpenText}` is false: write 1-2 genuine sentences thanking them for their score, show regret if Detractor, skip topic/staff/competitor sections, go directly to Closing.\n\nRule 2 — TOPIC RESPONSE: Address primary topic first, then negative, then positive, then neutral. Be thankful for positive, empathetic for negative. Use stronger accountability tone for HIGH/CRITICAL severity. If `{survey.recurringIssue}` = true, explicitly acknowledge the issue has come up before and commit to a concrete next step.\n\nRule 3 — SCORE-COMMENT MISMATCH: HIGH_SCORE_NEGATIVE_COMMENT → acknowledge generous score while taking negative feedback seriously. LOW_SCORE_POSITIVE_COMMENT → gently acknowledge appreciation while offering to understand what would have made the experience higher rated.\n\nRule 4 — STAFF: Positive sentiment → mention appreciation will be shared. Negative sentiment → do not name employees, acknowledge concern generally.\n\nRule 5 — COMPETITOR: Never name the competitor. Reinforce your strength on the compared aspect.\n\nRule 6 — CHURN RISK MITIGATION: HIGH or IMMINENT → include clear, personal commitment to resolution and offer direct contact path. MEDIUM → reaffirm investment in the relationship.\n\nRule 7 — ADVOCACY ASK: If `{advocacy_eligible}` = true AND respondent is Promoter/Satisfied AND no score-comment mismatch: invite them to share their experience publicly. Healthcare/Dental: soften to general appreciation invitation.\n\nRule 8 — CONTEXT SIGNALS: Appreciate continued engagement if `{Contact.surveycount}` > 1. Acknowledge long-standing relationship if tenure indicates it. Mention holiday warmly if timestamp matches. Tie in season if relevant.\n\nRule 9 — CLOSING: If `{contact_recommendation.recommend_contact}` = true: invite offline conversation using `{Location.phone}` and/or `{Location.email}`. If `{survey.escalate}` = true: route to senior contact within 24 hours.\n\nRule 10 — TONE BY SURVEY TYPE: NPS Detractor: empathetic, accountable, action-oriented. NPS Promoter: appreciative, relationship-reinforcing. CSAT low: focused on the specific transaction. CES high-effort: acknowledge friction explicitly. Pulse/short-form: keep response proportionally brief.\n\nRule 11 — LENGTH: Score-only response: 2-3 sentences. Standard with open-text: 4-7 sentences. High-severity or churn-risk: up to 9 sentences, never feel templated.\n\nAfter applying all rules, finalize the message by performing necessary translation to match `{survey.language}`.',
            outputFields: [
              { value: 'Survey.response', type: 'variable' },
            ],
          },
        },
      },
      {
        id: 'surveys-insights',
        sectionContext: 'survey-insights-agents',
        title: 'Survey insights agent',
        description: 'Summarizes recurring themes for PM and Design teams on a schedule.',
        steps: ['Weekly schedule', 'Cluster responses', 'Summarize themes', 'Share digest'],
      },
    ],
  },
  ticketing: {
    name: 'Ticketing',
    icon: 'shapes',
    description: 'Prioritize issues, automate handoffs, and maintain SLA discipline.',
    agents: [
      {
        id: 'ticketing-priority',
        title: 'Ticket priority agent',
        description: 'Scores incoming tickets by urgency, customer tier, and business impact.',
        steps: ['Ticket created', 'Extract severity', 'Set priority', 'Notify queue'],
      },
      {
        id: 'ticketing-sla',
        title: 'SLA rescue agent',
        description: 'Detects tickets near breach and escalates them to the next available owner.',
        steps: ['Hourly schedule', 'Find at-risk tickets', 'Escalate owner', 'Post update'],
      },
    ],
  },
  contacts: {
    name: 'Contacts',
    icon: 'group',
    description: 'Enrich profiles, clean duplicates, and trigger lifecycle moments.',
    agents: [
      {
        id: 'contacts-enrichment',
        title: 'Contact enrichment agent',
        description: 'Completes missing profile fields from approved sources and flags conflicts.',
        steps: ['New contact', 'Find missing fields', 'Enrich profile', 'Request review'],
      },
      {
        id: 'contacts-duplicate',
        title: 'Duplicate merge agent',
        description: 'Identifies probable duplicate contacts and prepares merge recommendations.',
        steps: ['Daily scan', 'Match contacts', 'Score confidence', 'Create merge task'],
      },
    ],
  },
  campaigns: {
    name: 'Campaigns',
    icon: 'campaign',
    description: 'Build campaign QA, targeting, performance, and follow-up automations.',
    agents: [
      {
        id: 'campaigns-qa',
        title: 'Campaign QA agent',
        description: 'Checks audience, content, links, and compliance before a campaign is launched.',
        steps: ['Pre-launch trigger', 'Validate setup', 'Branch by issue', 'Approve or block'],
      },
      {
        id: 'campaigns-optimizer',
        title: 'Campaign optimizer agent',
        description: 'Reviews campaign results and recommends copy, timing, and audience improvements.',
        steps: ['Weekly schedule', 'Analyze metrics', 'Generate recommendations', 'Share summary'],
      },
    ],
  },
  reports: {
    name: 'Reports',
    icon: 'pie_chart',
    description: 'Create recurring reporting workflows for teams and leadership.',
    agents: [
      {
        id: 'reports-digest',
        title: 'Report digest agent',
        description: 'Builds recurring performance digests for selected modules and recipients.',
        steps: ['Weekly schedule', 'Pull metrics', 'Generate digest', 'Send report'],
      },
      {
        id: 'reports-anomaly',
        title: 'Anomaly insight agent',
        description: 'Finds metric outliers and adds narrative context to reporting.',
        steps: ['Metric scan', 'Detect outlier', 'Explain driver', 'Share insight'],
      },
    ],
  },
  insights: {
    name: 'Insights',
    icon: 'lightbulb',
    description: 'Turn customer signals into actionable product and operations insights.',
    agents: [
      {
        id: 'insights-summary',
        title: 'Insight summary agent',
        description: 'Summarizes emerging themes from feedback, messages, and social mentions.',
        steps: ['Signal collection', 'Cluster themes', 'Generate summary', 'Route to POD'],
      },
      {
        id: 'insights-trend',
        title: 'Trend detection agent',
        description: 'Tracks fast-moving themes and alerts teams when trends become significant.',
        steps: ['Daily scan', 'Compare baseline', 'Score trend', 'Notify team'],
      },
    ],
  },
  competitors: {
    name: 'Competitors',
    icon: 'leaderboard',
    description: 'Monitor competitor movements, benchmarks, and reputation signals.',
    agents: [
      {
        id: 'competitors-monitoring',
        title: 'Competitor monitoring agent',
        description: 'Tracks competitor rating, listing, and content changes across markets.',
        steps: ['Scheduled scan', 'Compare competitors', 'Summarize changes', 'Alert owner'],
      },
      {
        id: 'competitors-benchmark',
        title: 'Benchmark summary agent',
        description: 'Summarizes where a business is winning or losing against local competitors.',
        steps: ['Monthly schedule', 'Pull benchmarks', 'Generate insights', 'Share plan'],
      },
    ],
  },
  settings: {
    name: 'Settings',
    icon: 'settings',
    description: 'Manage reusable agent templates, permissions, and framework defaults.',
    agents: [
      {
        id: 'settings-template-audit',
        title: 'Template audit agent',
        description: 'Reviews saved templates for missing owners, stale fields, or duplicate intent.',
        steps: ['Weekly schedule', 'Scan templates', 'Flag issues', 'Notify admins'],
      },
      {
        id: 'settings-permission-review',
        title: 'Permission review agent',
        description: 'Checks agent permissions and highlights risky or outdated access.',
        steps: ['Monthly schedule', 'Review access', 'Find risks', 'Create admin task'],
      },
    ],
  },
};

export const MODULE_ORDER = [
  'overview',
  'reviews',
  'inbox',
  'listings',
  'referrals',
  'payments',
  'appointments',
  'social',
  'surveys',
  'ticketing',
  'contacts',
  'campaigns',
  'reports',
  'insights',
  'competitors',
  'settings',
];

export function getModuleTemplates(moduleId, sectionId) {
  if (moduleId !== 'reviews' && moduleId !== 'surveys') return [];
  return (MODULE_DEFINITIONS[moduleId]?.agents || [])
    .filter((agent) => !sectionId || agent.sectionContext === sectionId);
}

export function getAllTemplates() {
  return MODULE_ORDER.flatMap((moduleId) =>
    getModuleTemplates(moduleId).map((agent) => ({
      ...agent,
      moduleId,
      moduleName: MODULE_DEFINITIONS[moduleId].name,
    }))
  );
}
